# Generated by Django 5.1.5 on 2025-02-09 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('folio', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=24, verbose_name='Tipo del dispositivo')),
                ('make', models.CharField(max_length=16, verbose_name='Marca del dispositivo')),
                ('model', models.CharField(max_length=16, verbose_name='Modelo del dispositivo')),
                ('sn', models.CharField(max_length=16, verbose_name='Número de serie')),
                ('extras', models.CharField(blank=True, max_length=16, null=True, verbose_name='Dispositivos extras')),
                ('status', models.CharField(choices=[('almacenado', 'Almacenado'), ('diagnosticado', 'Diagnosticado'), ('reparado', 'Reparado'), ('entregado', 'Entregado'), ('reingreso', 'Reingreso'), ('cancelado', 'Cancelado')], default='almacenado', max_length=13)),
                ('income_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de ingreso')),
                ('tentative_delivery_date', models.DateField(blank=True, null=True, verbose_name='Fecha tentativa de entrega')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('client_inf', models.TextField(verbose_name='Falla reportada por el cliente')),
                ('services', models.TextField(blank=True, null=True, verbose_name='Servicios aplicados')),
                ('extra_info', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('investment', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Gastos de refacciones')),
                ('total', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Costo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de la última actualización')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de la última actualización')),
            ],
            options={
                'verbose_name': 'Pagos',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='Nombre del servicio')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de la última actualización')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
