# Generated by Django 5.1.5 on 2025-02-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='big_risk',
            field=models.BooleanField(default=False, verbose_name='Número de serie'),
        ),
        migrations.AddField(
            model_name='device',
            name='ultimatum_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Ultimatum'),
        ),
        migrations.AddField(
            model_name='device',
            name='ultimatum_notification',
            field=models.BooleanField(default=False, verbose_name='Ultimatum Notificado'),
        ),
    ]
