# Generated by Django 5.1.5 on 2025-02-09 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_device_big_risk_device_ultimatum_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Empleado asignado'),
        ),
        migrations.AlterField(
            model_name='device',
            name='big_risk',
            field=models.BooleanField(default=False, verbose_name='Reparación de alto riesgo'),
        ),
    ]
