# Generated by Django 5.1.5 on 2025-02-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_device_assigned_to_alter_device_big_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='quote',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Cotización'),
        ),
    ]
