# Generated by Django 5.1.5 on 2025-02-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_device_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='total',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Cobro final'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(verbose_name='Cantidad del pago'),
        ),
    ]
