# Generated by Django 5.1.5 on 2025-02-16 01:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_device_total_alter_payment_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('adelanto_de_pago', 'Adelanto de pago'), ('rest_del_pago', 'Resto del pago')], max_length=16, verbose_name='Tipo de Pago')),
                ('amount', models.FloatField(verbose_name='Cantidad del pago')),
                ('payment_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de la última actualización')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Pago recibido por')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.device', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Pago del cliente',
                'verbose_name_plural': 'Pagos de los clientes',
            },
        ),
    ]
