# Generated by Django 5.1.5 on 2025-02-16 02:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_devicepayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DevicePayment',
            new_name='PaymentDevice',
        ),
        migrations.AlterModelOptions(
            name='paymentdevice',
            options={'verbose_name': 'Pago del cliente', 'verbose_name_plural': 'Pagos de clientes'},
        ),
    ]
