# Generated by Django 5.1.5 on 2025-02-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_devicepayment_paymentdevice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='total_paid',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total pagado'),
        ),
        migrations.AlterField(
            model_name='device',
            name='total',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Costo final'),
        ),
    ]
