# Generated by Django 5.1.5 on 2025-02-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_device_total_paid_alter_device_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='get_paid',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Por cobrar'),
        ),
        migrations.AlterField(
            model_name='device',
            name='total_paid',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Adelanto'),
        ),
    ]
