# Generated by Django 5.1.5 on 2025-02-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_rename_total_device_final_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentService',
            fields=[
            ],
            options={
                'verbose_name': 'Pagos de servicio',
                'verbose_name_plural': 'Pagos de servicios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.payment',),
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Pagos / Egreso', 'verbose_name_plural': 'Pagos / Egresos'},
        ),
        migrations.AlterModelOptions(
            name='paymentdevice',
            options={'verbose_name': 'Pago del cliente / Ingreso', 'verbose_name_plural': 'Pagos de clientes / Ingresos'},
        ),
        migrations.AlterField(
            model_name='device',
            name='investment',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Pago de refacciones'),
        ),
    ]
