# Generated by Django 5.1.5 on 2025-02-16 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_paymentservice_alter_payment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPayroll',
            fields=[
            ],
            options={
                'verbose_name': 'Pagos de Nómina',
                'verbose_name_plural': 'Pagos de Nómina',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.payment',),
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paymentdevice',
            options={'verbose_name': 'Pago del cliente', 'verbose_name_plural': 'Pagos de clientes'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Pago a empleado'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.service', verbose_name='Pago a servicio'),
        ),
    ]
