# Generated by Django 5.1.5 on 2025-02-21 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_paymentpayroll_alter_payment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(verbose_name='Costo del producto')),
                ('discount', models.IntegerField(default=0, verbose_name='Porcentaje de descuento')),
                ('real_cost', models.FloatField(verbose_name='Costo con descuento')),
                ('stock', models.FloatField(verbose_name='Existencias')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de la última actualización')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='addedby', to=settings.AUTH_USER_MODEL, verbose_name='Pago recibido por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.device', verbose_name='Dispositivo'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('nomina', 'Nómina'), ('cliente', 'Cliente'), ('servicio', 'Servicio')], default='nomina', max_length=8, verbose_name='Tipo de Pago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Pago a empleado'),
        ),
        migrations.DeleteModel(
            name='PaymentDevice',
        ),
        migrations.CreateModel(
            name='PaymentDevice',
            fields=[
            ],
            options={
                'verbose_name': 'Pagos de Clientes',
                'verbose_name_plural': 'Pagos de Clientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.payment',),
        ),
    ]
