# Generated by Django 5.1.5 on 2025-02-21 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_products_payment_added_by_payment_device_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='device',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='service',
        ),
        migrations.DeleteModel(
            name='PaymentDevice',
        ),
        migrations.DeleteModel(
            name='PaymentPayroll',
        ),
        migrations.DeleteModel(
            name='PaymentService',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
