# Generated by Django 5.1.5 on 2025-02-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_payment_added_by_remove_payment_device_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.AlterField(
            model_name='device',
            name='paid',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Pagos'),
        ),
    ]
