# Generated by Django 5.1.5 on 2025-02-22 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='real_cost',
        ),
    ]
