# Generated by Django 5.1.5 on 2025-02-21 19:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0015_remove_payment_added_by_remove_payment_device_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('nomina', 'Nómina'), ('cliente', 'Cliente'), ('servicio', 'Servicio')], max_length=8, verbose_name='Tipo de Pago')),
                ('amount', models.FloatField(verbose_name='Cantidad del pago')),
                ('payment_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de la última actualización')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addedby', to=settings.AUTH_USER_MODEL, verbose_name='Pago recibido por')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.device', verbose_name='Dispositivo')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Pago a empleado')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.service', verbose_name='Pago a servicio')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDevice',
            fields=[
            ],
            options={
                'verbose_name': 'Pagos de Clientes',
                'verbose_name_plural': 'Pagos de Clientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.payment',),
        ),
        migrations.CreateModel(
            name='PaymentPayroll',
            fields=[
            ],
            options={
                'verbose_name': 'Pagos de Nómina',
                'verbose_name_plural': 'Pagos de Nómina',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.payment',),
        ),
        migrations.CreateModel(
            name='PaymentService',
            fields=[
            ],
            options={
                'verbose_name': 'Pagos de servicio',
                'verbose_name_plural': 'Pagos de servicios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.payment',),
        ),
    ]
