# Generated by Django 5.1.5 on 2025-02-22 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_remove_product_discount_remove_product_real_cost'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentDevice',
        ),
        migrations.DeleteModel(
            name='PaymentPayroll',
        ),
        migrations.DeleteModel(
            name='PaymentService',
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
            ],
            options={
                'verbose_name': 'Pagos de Clientes',
                'verbose_name_plural': 'Pagos de Clientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.payment',),
        ),
        migrations.CreateModel(
            name='PayrollPayment',
            fields=[
            ],
            options={
                'verbose_name': 'Pagos de Nómina',
                'verbose_name_plural': 'Pagos de Nómina',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.payment',),
        ),
        migrations.CreateModel(
            name='ServicePayment',
            fields=[
            ],
            options={
                'verbose_name': 'Pagos de servicio',
                'verbose_name_plural': 'Pagos de servicios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.payment',),
        ),
        migrations.AddField(
            model_name='payment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Pago del Producto'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.device', verbose_name='Pago del cliente'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('nomina', 'Nómina'), ('cliente', 'Cliente'), ('servicio', 'Servicio'), ('producto', 'Producto')], max_length=8, verbose_name='Tipo de Pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.service', verbose_name='Pago del servicio'),
        ),
    ]
