# Generated by Django 5.1.5 on 2025-02-22 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_delete_paymentdevice_delete_paymentpayroll_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPayment',
            fields=[
            ],
            options={
                'verbose_name': 'Pagos de Producto',
                'verbose_name_plural': 'Pagos de Productos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.payment',),
        ),
        migrations.AlterModelOptions(
            name='servicepayment',
            options={'verbose_name': 'Pagos de Servicio', 'verbose_name_plural': 'Pagos de Servicios'},
        ),
    ]
