# Generated by Django 5.1.5 on 2025-02-23 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_product_sold_alter_product_stock'),
        ('payments', '0003_productpayment_alter_servicepayment_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerpayment',
            options={'verbose_name': 'Pagos a Reparacion', 'verbose_name_plural': 'Pagos a Reparaciones'},
        ),
        migrations.AlterModelOptions(
            name='productpayment',
            options={'verbose_name': 'Pagos a Producto', 'verbose_name_plural': 'Pagos a Productos'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.device', verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.service', verbose_name='Servicio'),
        ),
    ]
